// Code generated by languages/generate
// DO NOT EDIT!

package languages

import (
	"fmt"
	"strings"
)

const (
	// a LanguageType of type Assembly.
	Assembly LanguageType = iota
	// a LanguageType of type Bash.
	Bash
	// a LanguageType of type C.
	C
	// a LanguageType of type CSharp.
	CSharp
	// a LanguageType of type Cpp.
	Cpp
	// a LanguageType of type D.
	D
	// a LanguageType of type Go.
	Go
	// a LanguageType of type Haskell.
	Haskell
	// a LanguageType of type Java.
	Java
	// a LanguageType of type JavaScript.
	JavaScript
	// a LanguageType of type Julia.
	Julia
	// a LanguageType of type Kotlin.
	Kotlin
	// a LanguageType of type Lua.
	Lua
	// a LanguageType of type Ocaml.
	Ocaml
	// a LanguageType of type Perl.
	Perl
	// a LanguageType of type Php.
	Php
	// a LanguageType of type Python.
	Python
	// a LanguageType of type Ruby.
	Ruby
	// a LanguageType of type Rust.
	Rust
	// a LanguageType of type Scala.
	Scala
	// a LanguageType of type Swift.
	Swift
	// a LanguageType of type TypeScript.
	TypeScript
	// a LanguageType of type Unknown.
	Unknown
)

const _LanguageTypeName = "AssemblyBashCCSharpCppDGoHaskellJavaJavaScriptJuliaKotlinLuaOcamlPerlPhpPythonRubyRustScalaSwiftTypeScriptUnknown"

var _LanguageTypeNames = []string{
	_LanguageTypeName[0:8],
	_LanguageTypeName[8:12],
	_LanguageTypeName[12:13],
	_LanguageTypeName[13:19],
	_LanguageTypeName[19:22],
	_LanguageTypeName[22:23],
	_LanguageTypeName[23:25],
	_LanguageTypeName[25:32],
	_LanguageTypeName[32:36],
	_LanguageTypeName[36:46],
	_LanguageTypeName[46:51],
	_LanguageTypeName[51:57],
	_LanguageTypeName[57:60],
	_LanguageTypeName[60:65],
	_LanguageTypeName[65:69],
	_LanguageTypeName[69:72],
	_LanguageTypeName[72:78],
	_LanguageTypeName[78:82],
	_LanguageTypeName[82:86],
	_LanguageTypeName[86:91],
	_LanguageTypeName[91:96],
	_LanguageTypeName[96:106],
	_LanguageTypeName[106:113],
}

// LanguageTypeNames returns a list of possible string values of LanguageType.
func LanguageTypeNames() []string {
	tmp := make([]string, len(_LanguageTypeNames))
	copy(tmp, _LanguageTypeNames)
	return tmp
}

var _LanguageTypeMap = map[LanguageType]string{
	0:  _LanguageTypeName[0:8],
	1:  _LanguageTypeName[8:12],
	2:  _LanguageTypeName[12:13],
	3:  _LanguageTypeName[13:19],
	4:  _LanguageTypeName[19:22],
	5:  _LanguageTypeName[22:23],
	6:  _LanguageTypeName[23:25],
	7:  _LanguageTypeName[25:32],
	8:  _LanguageTypeName[32:36],
	9:  _LanguageTypeName[36:46],
	10: _LanguageTypeName[46:51],
	11: _LanguageTypeName[51:57],
	12: _LanguageTypeName[57:60],
	13: _LanguageTypeName[60:65],
	14: _LanguageTypeName[65:69],
	15: _LanguageTypeName[69:72],
	16: _LanguageTypeName[72:78],
	17: _LanguageTypeName[78:82],
	18: _LanguageTypeName[82:86],
	19: _LanguageTypeName[86:91],
	20: _LanguageTypeName[91:96],
	21: _LanguageTypeName[96:106],
	22: _LanguageTypeName[106:113],
}

// String implements the Stringer interface.
func (x LanguageType) String() string {
	if str, ok := _LanguageTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("LanguageType(%d)", x)
}

var _LanguageTypeValue = map[string]LanguageType{
	_LanguageTypeName[0:8]:                      0,
	strings.ToLower(_LanguageTypeName[0:8]):     0,
	_LanguageTypeName[8:12]:                     1,
	strings.ToLower(_LanguageTypeName[8:12]):    1,
	_LanguageTypeName[12:13]:                    2,
	strings.ToLower(_LanguageTypeName[12:13]):   2,
	_LanguageTypeName[13:19]:                    3,
	strings.ToLower(_LanguageTypeName[13:19]):   3,
	_LanguageTypeName[19:22]:                    4,
	strings.ToLower(_LanguageTypeName[19:22]):   4,
	_LanguageTypeName[22:23]:                    5,
	strings.ToLower(_LanguageTypeName[22:23]):   5,
	_LanguageTypeName[23:25]:                    6,
	strings.ToLower(_LanguageTypeName[23:25]):   6,
	_LanguageTypeName[25:32]:                    7,
	strings.ToLower(_LanguageTypeName[25:32]):   7,
	_LanguageTypeName[32:36]:                    8,
	strings.ToLower(_LanguageTypeName[32:36]):   8,
	_LanguageTypeName[36:46]:                    9,
	strings.ToLower(_LanguageTypeName[36:46]):   9,
	_LanguageTypeName[46:51]:                    10,
	strings.ToLower(_LanguageTypeName[46:51]):   10,
	_LanguageTypeName[51:57]:                    11,
	strings.ToLower(_LanguageTypeName[51:57]):   11,
	_LanguageTypeName[57:60]:                    12,
	strings.ToLower(_LanguageTypeName[57:60]):   12,
	_LanguageTypeName[60:65]:                    13,
	strings.ToLower(_LanguageTypeName[60:65]):   13,
	_LanguageTypeName[65:69]:                    14,
	strings.ToLower(_LanguageTypeName[65:69]):   14,
	_LanguageTypeName[69:72]:                    15,
	strings.ToLower(_LanguageTypeName[69:72]):   15,
	_LanguageTypeName[72:78]:                    16,
	strings.ToLower(_LanguageTypeName[72:78]):   16,
	_LanguageTypeName[78:82]:                    17,
	strings.ToLower(_LanguageTypeName[78:82]):   17,
	_LanguageTypeName[82:86]:                    18,
	strings.ToLower(_LanguageTypeName[82:86]):   18,
	_LanguageTypeName[86:91]:                    19,
	strings.ToLower(_LanguageTypeName[86:91]):   19,
	_LanguageTypeName[91:96]:                    20,
	strings.ToLower(_LanguageTypeName[91:96]):   20,
	_LanguageTypeName[96:106]:                   21,
	strings.ToLower(_LanguageTypeName[96:106]):  21,
	_LanguageTypeName[106:113]:                  22,
	strings.ToLower(_LanguageTypeName[106:113]): 22,
}

// ParseLanguageType attempts to convert a string to a LanguageType
func ParseLanguageType(name string) (LanguageType, error) {
	if x, ok := _LanguageTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _LanguageTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return LanguageType(0), fmt.Errorf("%s is not a valid LanguageType, try [%s]", name, strings.Join(_LanguageTypeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x LanguageType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *LanguageType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseLanguageType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
