// Code generated by languages/generate
// DO NOT EDIT!

package languages

import (
	"fmt"
	"strings"
)

const (
	// Assembly is a LanguageType of type Assembly.
	Assembly LanguageType = iota
	// Bash is a LanguageType of type Bash.
	Bash
	// C is a LanguageType of type C.
	C
	// Clojure is a LanguageType of type Clojure.
	Clojure
	// CoffeeScript is a LanguageType of type CoffeeScript.
	CoffeeScript
	// Cpp is a LanguageType of type Cpp.
	Cpp
	// CSharp is a LanguageType of type CSharp.
	CSharp
	// D is a LanguageType of type D.
	D
	// Elixir is a LanguageType of type Elixir.
	Elixir
	// Go is a LanguageType of type Go.
	Go
	// Groovy is a LanguageType of type Groovy.
	Groovy
	// Haskell is a LanguageType of type Haskell.
	Haskell
	// Java is a LanguageType of type Java.
	Java
	// JavaScript is a LanguageType of type JavaScript.
	JavaScript
	// Julia is a LanguageType of type Julia.
	Julia
	// Kotlin is a LanguageType of type Kotlin.
	Kotlin
	// Lua is a LanguageType of type Lua.
	Lua
	// Nim is a LanguageType of type Nim.
	Nim
	// Ocaml is a LanguageType of type Ocaml.
	Ocaml
	// Perl is a LanguageType of type Perl.
	Perl
	// Php is a LanguageType of type Php.
	Php
	// Python is a LanguageType of type Python.
	Python
	// Raku is a LanguageType of type Raku.
	Raku
	// Ruby is a LanguageType of type Ruby.
	Ruby
	// Rust is a LanguageType of type Rust.
	Rust
	// Scala is a LanguageType of type Scala.
	Scala
	// Swift is a LanguageType of type Swift.
	Swift
	// TypeScript is a LanguageType of type TypeScript.
	TypeScript
)

const _LanguageTypeName = "AssemblyBashCClojureCoffeeScriptCppCSharpDElixirGoGroovyHaskellJavaJavaScriptJuliaKotlinLuaNimOcamlPerlPhpPythonRakuRubyRustScalaSwiftTypeScript"
const _LanguageTypeFileName = "main.asmmain.bashmain.cmain.cljmain.coffeemain.cppmain.csmain.dmain.exmain.gomain.groovymain.hsMain.javamain.jsmain.jlMain.ktmain.luamain.nimmain.mlmain.plmain.phpmain.pymain.rakumain.rbmain.rustmain.scalamain.swiftmain.ts"

var _LanguageTypeNames = []string{
	_LanguageTypeName[0:8],
	_LanguageTypeName[8:12],
	_LanguageTypeName[12:13],
	_LanguageTypeName[13:20],
	_LanguageTypeName[20:32],
	_LanguageTypeName[32:35],
	_LanguageTypeName[35:41],
	_LanguageTypeName[41:42],
	_LanguageTypeName[42:48],
	_LanguageTypeName[48:50],
	_LanguageTypeName[50:56],
	_LanguageTypeName[56:63],
	_LanguageTypeName[63:67],
	_LanguageTypeName[67:77],
	_LanguageTypeName[77:82],
	_LanguageTypeName[82:88],
	_LanguageTypeName[88:91],
	_LanguageTypeName[91:94],
	_LanguageTypeName[94:99],
	_LanguageTypeName[99:103],
	_LanguageTypeName[103:106],
	_LanguageTypeName[106:112],
	_LanguageTypeName[112:116],
	_LanguageTypeName[116:120],
	_LanguageTypeName[120:124],
	_LanguageTypeName[124:129],
	_LanguageTypeName[129:134],
	_LanguageTypeName[134:144],
}

// LanguageTypeNames returns a list of possible string values of LanguageType.
func LanguageTypeNames() []string {
	tmp := make([]string, len(_LanguageTypeNames))
	copy(tmp, _LanguageTypeNames)
	return tmp
}

var _LanguageTypeFileNames = []string{
	_LanguageTypeFileName[0:8],
	_LanguageTypeFileName[8:17],
	_LanguageTypeFileName[17:23],
	_LanguageTypeFileName[23:31],
	_LanguageTypeFileName[31:42],
	_LanguageTypeFileName[42:50],
	_LanguageTypeFileName[50:57],
	_LanguageTypeFileName[57:63],
	_LanguageTypeFileName[63:70],
	_LanguageTypeFileName[70:77],
	_LanguageTypeFileName[77:88],
	_LanguageTypeFileName[88:95],
	_LanguageTypeFileName[95:104],
	_LanguageTypeFileName[104:111],
	_LanguageTypeFileName[111:118],
	_LanguageTypeFileName[118:125],
	_LanguageTypeFileName[125:133],
	_LanguageTypeFileName[133:141],
	_LanguageTypeFileName[141:148],
	_LanguageTypeFileName[148:155],
	_LanguageTypeFileName[155:163],
	_LanguageTypeFileName[163:170],
	_LanguageTypeFileName[170:179],
	_LanguageTypeFileName[179:186],
	_LanguageTypeFileName[186:195],
	_LanguageTypeFileName[195:205],
	_LanguageTypeFileName[205:215],
	_LanguageTypeFileName[215:222],
}

func LanguageTypeFileNames() []string {
	tmp := make([]string, len(_LanguageTypeFileNames))
	copy(tmp, _LanguageTypeFileNames)
	return tmp
}

var _LanguageTypeMap = map[LanguageType]string{
	0:  _LanguageTypeName[0:8],
	1:  _LanguageTypeName[8:12],
	2:  _LanguageTypeName[12:13],
	3:  _LanguageTypeName[13:20],
	4:  _LanguageTypeName[20:32],
	5:  _LanguageTypeName[32:35],
	6:  _LanguageTypeName[35:41],
	7:  _LanguageTypeName[41:42],
	8:  _LanguageTypeName[42:48],
	9:  _LanguageTypeName[48:50],
	10: _LanguageTypeName[50:56],
	11: _LanguageTypeName[56:63],
	12: _LanguageTypeName[63:67],
	13: _LanguageTypeName[67:77],
	14: _LanguageTypeName[77:82],
	15: _LanguageTypeName[82:88],
	16: _LanguageTypeName[88:91],
	17: _LanguageTypeName[91:94],
	18: _LanguageTypeName[94:99],
	19: _LanguageTypeName[99:103],
	20: _LanguageTypeName[103:106],
	21: _LanguageTypeName[106:112],
	22: _LanguageTypeName[112:116],
	23: _LanguageTypeName[116:120],
	24: _LanguageTypeName[120:124],
	25: _LanguageTypeName[124:129],
	26: _LanguageTypeName[129:134],
	27: _LanguageTypeName[134:144],
}
var _LanguageTypeFileNameMap = map[LanguageType]string{
	0:  _LanguageTypeFileName[0:8],
	1:  _LanguageTypeFileName[8:17],
	2:  _LanguageTypeFileName[17:23],
	3:  _LanguageTypeFileName[23:31],
	4:  _LanguageTypeFileName[31:42],
	5:  _LanguageTypeFileName[42:50],
	6:  _LanguageTypeFileName[50:57],
	7:  _LanguageTypeFileName[57:63],
	8:  _LanguageTypeFileName[63:70],
	9:  _LanguageTypeFileName[70:77],
	10: _LanguageTypeFileName[77:88],
	11: _LanguageTypeFileName[88:95],
	12: _LanguageTypeFileName[95:104],
	13: _LanguageTypeFileName[104:111],
	14: _LanguageTypeFileName[111:118],
	15: _LanguageTypeFileName[118:125],
	16: _LanguageTypeFileName[125:133],
	17: _LanguageTypeFileName[133:141],
	18: _LanguageTypeFileName[141:148],
	19: _LanguageTypeFileName[148:155],
	20: _LanguageTypeFileName[155:163],
	21: _LanguageTypeFileName[163:170],
	22: _LanguageTypeFileName[170:179],
	23: _LanguageTypeFileName[179:186],
	24: _LanguageTypeFileName[186:195],
	25: _LanguageTypeFileName[195:205],
	26: _LanguageTypeFileName[205:215],
	27: _LanguageTypeFileName[215:222],
}

// String implements the Stringer interface.
func (x LanguageType) String() string {
	if str, ok := _LanguageTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("LanguageType(%d)", x)
}

func (x LanguageType) FileName() string {
	if str, ok := _LanguageTypeFileNameMap[x]; ok {
		return str
	}
	return "unknown"
}

var _LanguageTypeValue = map[string]LanguageType{
	_LanguageTypeName[0:8]:                      0,
	strings.ToLower(_LanguageTypeName[0:8]):     0,
	_LanguageTypeName[8:12]:                     1,
	strings.ToLower(_LanguageTypeName[8:12]):    1,
	_LanguageTypeName[12:13]:                    2,
	strings.ToLower(_LanguageTypeName[12:13]):   2,
	_LanguageTypeName[13:20]:                    3,
	strings.ToLower(_LanguageTypeName[13:20]):   3,
	_LanguageTypeName[20:32]:                    4,
	strings.ToLower(_LanguageTypeName[20:32]):   4,
	_LanguageTypeName[32:35]:                    5,
	strings.ToLower(_LanguageTypeName[32:35]):   5,
	_LanguageTypeName[35:41]:                    6,
	strings.ToLower(_LanguageTypeName[35:41]):   6,
	_LanguageTypeName[41:42]:                    7,
	strings.ToLower(_LanguageTypeName[41:42]):   7,
	_LanguageTypeName[42:48]:                    8,
	strings.ToLower(_LanguageTypeName[42:48]):   8,
	_LanguageTypeName[48:50]:                    9,
	strings.ToLower(_LanguageTypeName[48:50]):   9,
	_LanguageTypeName[50:56]:                    10,
	strings.ToLower(_LanguageTypeName[50:56]):   10,
	_LanguageTypeName[56:63]:                    11,
	strings.ToLower(_LanguageTypeName[56:63]):   11,
	_LanguageTypeName[63:67]:                    12,
	strings.ToLower(_LanguageTypeName[63:67]):   12,
	_LanguageTypeName[67:77]:                    13,
	strings.ToLower(_LanguageTypeName[67:77]):   13,
	_LanguageTypeName[77:82]:                    14,
	strings.ToLower(_LanguageTypeName[77:82]):   14,
	_LanguageTypeName[82:88]:                    15,
	strings.ToLower(_LanguageTypeName[82:88]):   15,
	_LanguageTypeName[88:91]:                    16,
	strings.ToLower(_LanguageTypeName[88:91]):   16,
	_LanguageTypeName[91:94]:                    17,
	strings.ToLower(_LanguageTypeName[91:94]):   17,
	_LanguageTypeName[94:99]:                    18,
	strings.ToLower(_LanguageTypeName[94:99]):   18,
	_LanguageTypeName[99:103]:                   19,
	strings.ToLower(_LanguageTypeName[99:103]):  19,
	_LanguageTypeName[103:106]:                  20,
	strings.ToLower(_LanguageTypeName[103:106]): 20,
	_LanguageTypeName[106:112]:                  21,
	strings.ToLower(_LanguageTypeName[106:112]): 21,
	_LanguageTypeName[112:116]:                  22,
	strings.ToLower(_LanguageTypeName[112:116]): 22,
	_LanguageTypeName[116:120]:                  23,
	strings.ToLower(_LanguageTypeName[116:120]): 23,
	_LanguageTypeName[120:124]:                  24,
	strings.ToLower(_LanguageTypeName[120:124]): 24,
	_LanguageTypeName[124:129]:                  25,
	strings.ToLower(_LanguageTypeName[124:129]): 25,
	_LanguageTypeName[129:134]:                  26,
	strings.ToLower(_LanguageTypeName[129:134]): 26,
	_LanguageTypeName[134:144]:                  27,
	strings.ToLower(_LanguageTypeName[134:144]): 27,
}

// ParseLanguageType attempts to convert a string to a LanguageType
func ParseLanguageType(name string) (LanguageType, error) {
	if x, ok := _LanguageTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _LanguageTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return LanguageType(0), fmt.Errorf("%s is not a valid LanguageType, try [%s]", name, strings.Join(_LanguageTypeNames, ", "))
}

// MarshalText implements the text marshaller method
func (x LanguageType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *LanguageType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseLanguageType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
