package constants

const (
	VERSION_NOT_FOUND_ERROR  string = "VERSION_NOT_FOUND_ERROR"
	LANGUAGE_NOT_FOUND_ERROR string = "LANGUAGE_NOT_FOUND_ERROR"
	NO_TESTDATA_ERROR        string = "NO_TESTDATA_ERROR"
	TESTDATA_LENGTH_ERROR    string = "TESTDATA_LENGTH_ERROR"
	CODE_EMPTY_ERROR         string = "CODE_EMPTY_ERROR"
)
