// Code generated by go-enum
// DO NOT EDIT!

package pkg

import (
	"fmt"
	"strings"
)

const (
	// Assembly is a LanguageType of type Assembly.
	Assembly LanguageType = iota
	// Bash is a LanguageType of type Bash.
	Bash
	// C is a LanguageType of type C.
	C
	// Clojure is a LanguageType of type Clojure.
	Clojure
	// CoffeeScript is a LanguageType of type CoffeeScript.
	CoffeeScript
	// Cpp is a LanguageType of type Cpp.
	Cpp
	// Csharp is a LanguageType of type Csharp.
	Csharp
	// D is a LanguageType of type D.
	D
	// Elixir is a LanguageType of type Elixir.
	Elixir
	// Erlang is a LanguageType of type Erlang.
	Erlang
	// Fsharp is a LanguageType of type Fsharp.
	Fsharp
	// Go is a LanguageType of type Go.
	Go
	// Groovy is a LanguageType of type Groovy.
	Groovy
	// Haskell is a LanguageType of type Haskell.
	Haskell
	// Java is a LanguageType of type Java.
	Java
	// JavaScript is a LanguageType of type JavaScript.
	JavaScript
	// Julia is a LanguageType of type Julia.
	Julia
	// Kotlin is a LanguageType of type Kotlin.
	Kotlin
	// Lua is a LanguageType of type Lua.
	Lua
	// Mercury is a LanguageType of type Mercury.
	Mercury
	// Nim is a LanguageType of type Nim.
	Nim
	// Ocaml is a LanguageType of type Ocaml.
	Ocaml
	// Perl is a LanguageType of type Perl.
	Perl
	// Php is a LanguageType of type Php.
	Php
	// Python is a LanguageType of type Python.
	Python
	// Raku is a LanguageType of type Raku.
	Raku
	// Ruby is a LanguageType of type Ruby.
	Ruby
	// Rust is a LanguageType of type Rust.
	Rust
	// Scala is a LanguageType of type Scala.
	Scala
	// Swift is a LanguageType of type Swift.
	Swift
	// TypeScript is a LanguageType of type TypeScript.
	TypeScript
)

const _LanguageTypeName = "AssemblyBashCClojureCoffeeScriptCppCsharpDElixirErlangFsharpGoGroovyHaskellJavaJavaScriptJuliaKotlinLuaMercuryNimOcamlPerlPhpPythonRakuRubyRustScalaSwiftTypeScript"

var _LanguageTypeMap = map[LanguageType]string{
	0:  _LanguageTypeName[0:8],
	1:  _LanguageTypeName[8:12],
	2:  _LanguageTypeName[12:13],
	3:  _LanguageTypeName[13:20],
	4:  _LanguageTypeName[20:32],
	5:  _LanguageTypeName[32:35],
	6:  _LanguageTypeName[35:41],
	7:  _LanguageTypeName[41:42],
	8:  _LanguageTypeName[42:48],
	9:  _LanguageTypeName[48:54],
	10: _LanguageTypeName[54:60],
	11: _LanguageTypeName[60:62],
	12: _LanguageTypeName[62:68],
	13: _LanguageTypeName[68:75],
	14: _LanguageTypeName[75:79],
	15: _LanguageTypeName[79:89],
	16: _LanguageTypeName[89:94],
	17: _LanguageTypeName[94:100],
	18: _LanguageTypeName[100:103],
	19: _LanguageTypeName[103:110],
	20: _LanguageTypeName[110:113],
	21: _LanguageTypeName[113:118],
	22: _LanguageTypeName[118:122],
	23: _LanguageTypeName[122:125],
	24: _LanguageTypeName[125:131],
	25: _LanguageTypeName[131:135],
	26: _LanguageTypeName[135:139],
	27: _LanguageTypeName[139:143],
	28: _LanguageTypeName[143:148],
	29: _LanguageTypeName[148:153],
	30: _LanguageTypeName[153:163],
}

// String implements the Stringer interface.
func (x LanguageType) String() string {
	if str, ok := _LanguageTypeMap[x]; ok {
		return str
	}
	return fmt.Sprintf("LanguageType(%d)", x)
}

var _LanguageTypeValue = map[string]LanguageType{
	_LanguageTypeName[0:8]:                      0,
	strings.ToLower(_LanguageTypeName[0:8]):     0,
	_LanguageTypeName[8:12]:                     1,
	strings.ToLower(_LanguageTypeName[8:12]):    1,
	_LanguageTypeName[12:13]:                    2,
	strings.ToLower(_LanguageTypeName[12:13]):   2,
	_LanguageTypeName[13:20]:                    3,
	strings.ToLower(_LanguageTypeName[13:20]):   3,
	_LanguageTypeName[20:32]:                    4,
	strings.ToLower(_LanguageTypeName[20:32]):   4,
	_LanguageTypeName[32:35]:                    5,
	strings.ToLower(_LanguageTypeName[32:35]):   5,
	_LanguageTypeName[35:41]:                    6,
	strings.ToLower(_LanguageTypeName[35:41]):   6,
	_LanguageTypeName[41:42]:                    7,
	strings.ToLower(_LanguageTypeName[41:42]):   7,
	_LanguageTypeName[42:48]:                    8,
	strings.ToLower(_LanguageTypeName[42:48]):   8,
	_LanguageTypeName[48:54]:                    9,
	strings.ToLower(_LanguageTypeName[48:54]):   9,
	_LanguageTypeName[54:60]:                    10,
	strings.ToLower(_LanguageTypeName[54:60]):   10,
	_LanguageTypeName[60:62]:                    11,
	strings.ToLower(_LanguageTypeName[60:62]):   11,
	_LanguageTypeName[62:68]:                    12,
	strings.ToLower(_LanguageTypeName[62:68]):   12,
	_LanguageTypeName[68:75]:                    13,
	strings.ToLower(_LanguageTypeName[68:75]):   13,
	_LanguageTypeName[75:79]:                    14,
	strings.ToLower(_LanguageTypeName[75:79]):   14,
	_LanguageTypeName[79:89]:                    15,
	strings.ToLower(_LanguageTypeName[79:89]):   15,
	_LanguageTypeName[89:94]:                    16,
	strings.ToLower(_LanguageTypeName[89:94]):   16,
	_LanguageTypeName[94:100]:                   17,
	strings.ToLower(_LanguageTypeName[94:100]):  17,
	_LanguageTypeName[100:103]:                  18,
	strings.ToLower(_LanguageTypeName[100:103]): 18,
	_LanguageTypeName[103:110]:                  19,
	strings.ToLower(_LanguageTypeName[103:110]): 19,
	_LanguageTypeName[110:113]:                  20,
	strings.ToLower(_LanguageTypeName[110:113]): 20,
	_LanguageTypeName[113:118]:                  21,
	strings.ToLower(_LanguageTypeName[113:118]): 21,
	_LanguageTypeName[118:122]:                  22,
	strings.ToLower(_LanguageTypeName[118:122]): 22,
	_LanguageTypeName[122:125]:                  23,
	strings.ToLower(_LanguageTypeName[122:125]): 23,
	_LanguageTypeName[125:131]:                  24,
	strings.ToLower(_LanguageTypeName[125:131]): 24,
	_LanguageTypeName[131:135]:                  25,
	strings.ToLower(_LanguageTypeName[131:135]): 25,
	_LanguageTypeName[135:139]:                  26,
	strings.ToLower(_LanguageTypeName[135:139]): 26,
	_LanguageTypeName[139:143]:                  27,
	strings.ToLower(_LanguageTypeName[139:143]): 27,
	_LanguageTypeName[143:148]:                  28,
	strings.ToLower(_LanguageTypeName[143:148]): 28,
	_LanguageTypeName[148:153]:                  29,
	strings.ToLower(_LanguageTypeName[148:153]): 29,
	_LanguageTypeName[153:163]:                  30,
	strings.ToLower(_LanguageTypeName[153:163]): 30,
}

// ParseLanguageType attempts to convert a string to a LanguageType
func ParseLanguageType(name string) (LanguageType, error) {
	if x, ok := _LanguageTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _LanguageTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return LanguageType(0), fmt.Errorf("%s is not a valid LanguageType", name)
}

// MarshalText implements the text marshaller method
func (x LanguageType) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method
func (x *LanguageType) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseLanguageType(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
